print("All Spades:")
print(Deck.allSpades)
print("")
print("All Diamonds:")
print(Deck.allDiamonds)
print("")
print("All Hearts:")
print(Deck.allHearts)
print("")
print("All Clubs:")
print(Deck.allClubs)
print("")
print("All Cards:")
print(Deck.allCards)